### ISSUE TITLE
rota_model_weight not found

### ISSUE THREAD

**Issue by imerelli** [thuxugang/opus_mut#3]
Hi, I have a problem running opus-but. In the end there is a file that it could not be found.
./Mut/models/1/rota_model_weight
Can you help me with this error?

python run_opus_mut.py
2023-12-06 15:57:33.102023: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-12-06 15:57:52.403166: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-12-06 15:57:52.404939: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2023-12-06 15:57:54.320273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:3b:00.0 name: NVIDIA A100-PCIE-80GB computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 79.10GiB deviceMemoryBandwidth: 1.76TiB/s
2023-12-06 15:57:54.320312: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-12-06 15:57:54.332054: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2023-12-06 15:57:54.332163: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2023-12-06 15:57:54.338664: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2023-12-06 15:57:54.342752: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2023-12-06 15:57:54.349358: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2023-12-06 15:57:54.354895: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2023-12-06 15:57:54.368042: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2023-12-06 15:57:54.375938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2023-12-06 15:57:54.376622: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA                                                                                                       
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-06 15:57:54.380309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:3b:00.0 name: NVIDIA A100-PCIE-80GB computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 79.10GiB deviceMemoryBandwidth: 1.76TiB/s
2023-12-06 15:57:54.380328: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-12-06 15:57:54.380343: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2023-12-06 15:57:54.380349: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2023-12-06 15:57:54.380356: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2023-12-06 15:57:54.380362: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2023-12-06 15:57:54.380368: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2023-12-06 15:57:54.380374: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2023-12-06 15:57:54.380380: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2023-12-06 15:57:54.385658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2023-12-06 15:57:54.385686: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-12-06 16:01:08.277652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-12-06 16:01:08.277714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2023-12-06 16:01:08.277731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2023-12-06 16:01:08.291966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 75603 MB memory) -> physical GPU (device: 0, name: NVIDIA A100-PCIE-80GB, pci bus id: 0000:3b:00.0, compute capability: 8.0)                                                                                            
2023-12-06 16:01:08.292338: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
use rota model...
load model: rota4p1
Traceback (most recent call last):
  File "/opt/tools/deg/miniforge3/envs/mut/lib/python3.7/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./Mut/models/1/rota_model_weight

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_opus_mut.py", line 23, in <module>
    from Mut.inference import run_Mut
  File "/DATA/34/CXCR4/OpusMut/Mut/inference.py", line 15, in <module>
    from Mut.inference_models import test_infer_step
  File "/DATA/34/CXCR4/OpusMut/Mut/inference_models.py", line 30, in <module>
    model_rota1.load_model()
  File "/DATA/34/CXCR4/OpusMut/Mut/my_model.py", line 85, in load_model
    self.load_weights(os.path.join(self.params["save_path"], 'rota_model_weight'))
  File "/opt/tools/deg/miniforge3/envs/mut/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2199, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/opt/tools/deg/miniforge3/envs/mut/lib/python3.7/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/opt/tools/deg/miniforge3/envs/mut/lib/python3.7/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./Mut/models/1/rota_model_weight

**Comment by thuxugang** [comment]
Hi, the standalone version of OPUS-Mut as well as its pretrained models can be downloaded from https://drive.google.com/file/d/1ZpFjghkqP5vsIpOk1bYwFyhci7FeNPPD/view?usp=sharing
